[game]
hostname
desc
soft_max_players
panic_bunker.enable_without_admins
panic_bunker.disable_with_admins
panic_bunker.min_overall_hours

[shuttle]
emergency_early_launch_allowed

[worldgen]
enabled

[ooc]
enable_during_round

[admin]
see_own_notes
deadmin_on_join
bypass_max_players

[ban]
hardware_ids = true

[build]
fork_id


[hub]
advertise
tags
hub_urls

[infolinks]
discord
forum
github
website
wiki
patreon
bug_report
appeal


[net]
tickrate
port
lidgren_log_warning = false
lidgren_log_error = false
log_late_msg = false

[status]
bind
connectaddress

[database]
engine
pg_host
pg_port
pg_database
pg_username
pg_password


[log]
enabled = false

[adminlogs]
server_name

[metrics]
enabled
host = "*"
port


[console]
login_host_user
